# Generated by Django 6.0.5 on 2026-05-12 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_task_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
    ]
