# Generated by Django 6.0.5 on 2026-06-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0003_alter_workspacemembership_user_taskattachment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskattachment',
            old_name='upload_by',
            new_name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='taskattachment',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='taskattachment',
            name='file',
            field=models.FileField(upload_to='attachments/'),
        ),
    ]
