# Generated by Django 6.0.5 on 2026-06-20 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0005_alter_taskattachment_file_activitylog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='object_id',
        ),
    ]
