# Generated by Django 6.0.5 on 2026-05-26 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0008_workspacemembership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='members',
        ),
    ]
