# Generated by Django 6.0.5 on 2026-05-26 10:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0009_remove_workspace_members'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='workspaces_member', through='task_manager.WorkSpaceMembership', to=settings.AUTH_USER_MODEL),
        ),
    ]
